

version: "3.9"

services: 
 ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama

 api: 
    build: .
    container_name: sentence-making-api
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434


volumes:
  ollama_data:
    